#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first terms will be: 1,2,3,5,8,13,21,34,55,89,…
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.

# Define the upper limit
limit = 4000000

# Initialize first two Fibonacci numbers
a, b = 1, 2
sum_of_even_terms = 0

# Loop until the next term exceeds the limit
while a < limit:
  # Check if the current term is even
  if a % 2 == 0:
    sum_of_even_terms += a

  # Generate the next term in the sequence
  a, b = b, a + b

# Print the final sum
print(sum_of_even_terms)
